---
- name: Ensure endlessh is present
  package:
    name: endlessh
    state: present
  become: true

- name: Ensure systemd endlessh.service is enabled and started
  systemd:
    name: endlessh
    state: started
    enabled: true
  become: true

- name: Set `cap_net_bind_service+ep` on `/usr/bin/endlessh`
  community.general.capabilities:
    path: /usr/bin/endlessh
    capability: cap_net_bind_service+ep
    state: present
  become: true
  notify:
    - handler-reload-systemd-daemon (trallnag.endlessh)
    - handler-restart-endlessh-systemd-service (trallnag.endlessh)

- name: Place the config file
  template:
    src: "{{ role_path }}/templates/config"
    dest: /etc/endlessh/config
    owner: root
    group: root
    mode: "0655"
  become: true
  notify:
    - handler-restart-endlessh-systemd-service (trallnag.endlessh)

- name: Place the service file for systemd
  copy:
    src: "{{ role_path }}/files/endlessh.service"
    dest: /etc/systemd/system/endlessh.service
    owner: root
    group: root
    mode: "0644"
  become: true
  notify:
    - handler-reload-systemd-daemon (trallnag.endlessh)
    - handler-restart-endlessh-systemd-service (trallnag.endlessh)

- name: Flush handlers
  meta: flush_handlers

- name: Test if port is open and used by endlessh
  shell: |
    set -o pipefail
    ss -tulpn | grep :{{ endlessh_listen_port }}
    if ! ss -tulpn | grep :{{ endlessh_listen_port }} | grep -q endlessh
    then
      echo status=failed
    fi
  args:
    executable: /bin/bash
  register: task_setcap
  changed_when: "'status=changed' in task_setcap.stdout"
  failed_when: "'status=failed' in task_setcap.stdout"
  become: true
