- name: Stop and disable the systemd endlessh service
  systemd:
    name: endlessh
    state: stopped
    enabled: false
  become: true

- name: Ensure endlessh is absent
  apt:
    name: endlessh
    state: absent
  become: true

- name: Ensure `/etc/endlessh/` is absent
  file:
    state: absent
    path: /etc/endlessh/
  become: true

- name: Ensure that `/etc/systemd/system/endlessh.service` is absent
  file:
    state: absent
    path: /etc/systemd/system/endlessh.service
  become: true
  notify:
    - handler-reload-systemd-daemon (trallnag.endlessh)
    - handler-systemd-reset-failed (trallnag.endlessh)

- name: Ensure that `/usr/lib/systemd/system/endlessh.service` is absent
  file:
    state: absent
    path: /usr/lib/systemd/system/endlessh.service
  become: true
  notify:
    - handler-reload-systemd-daemon (trallnag.endlessh)
    - handler-systemd-reset-failed (trallnag.endlessh)

- name: Flush handlers
  meta: flush_handlers
