- name: Ensure endlessh is absent and purged
  apt:
    name: endlessh
    state: absent
    purge: true
  become: true

- name: Ensure systemd endlessh.service is stopped and disabled if exists
  shell: |
    set -o pipefail

    service=endlessh.service

    if systemctl list-unit-files | grep -q "^$service"
    then
      systemctl stop $service
      systemctl disable $service

      if ! systemctl list-unit-files | grep -q "^$service"
      then
        echo status=changed
      else
        echo status=failed
      fi
    fi
  args:
    executable: /bin/bash
  register: task
  changed_when: "'status=changed' in task.stdout"
  failed_when: "'status=failed' in task.stdout"
  become: true

- name: Ensure that `/etc/systemd/system/endlessh.service` is absent
  file:
    state: absent
    path: /etc/systemd/system/endlessh.service
  become: true
  notify:
    - handler-reload-systemd-daemon (trallnag.endlessh)
    - handler-systemd-reset-failed (trallnag.endlessh)

- name: Ensure that `/usr/lib/systemd/system/endlessh.service` is absent
  file:
    state: absent
    path: /usr/lib/systemd/system/endlessh.service
  become: true
  notify:
    - handler-reload-systemd-daemon (trallnag.endlessh)
    - handler-systemd-reset-failed (trallnag.endlessh)

- name: Ensure `/etc/init.d/endlessh` is absent
  file:
    state: absent
    path: /etc/init.d/endlessh
  become: true

- name: Ensure `/etc/endlessh/` is absent
  file:
    state: absent
    path: /etc/endlessh/
  become: true
